# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Contacts Map Geoprocessing Script.py
# Created on: 2014-10-23 14:49:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Const_Reg_Feature = "Database Connections\\GDB_ASSETS.sde\\GDB_Assets.ASSETS_ADMIN.Boundary_ConstructionRegions"
Const_Reg_Contact_View = "GDB_Assets.Assets_Admin.Contact_Const"
GDB_ASSETS_sde = "Database Connections\\GDB_ASSETS.sde"
District_Mileages_Feature = "GDB_Assets.ASSETS_ADMIN.MATS_District_Mileages_1"
OPSDistrictTowns_Feature = "GDB_Assets.ASSETS_ADMIN.Boundary_OPSDistrictTowns"
Contact_Dist_View = "Database Connections\\GDB_ASSETS.sde\\GDB_Assets.Assets_Admin.Contact_Dist"
Const_Reg_Contact_GeoTable = "Database Connections\\GDB_ASSETS.sde\\GDB_Assets.ASSETS_ADMIN.Const_Reg_Contact_GeoTable"
Dist_Cont_GeoTable = "Database Connections\\GDB_ASSETS.sde\\GDB_Assets.ASSETS_ADMIN.Dist_Cont_GeoTable"
Dist_Mile_Feature_Dissolved = "Database Connections\\GDB_ASSETS.sde\\GDB_Assets.ASSETS_ADMIN.Dist_Mile_Feature_Dissolved"
Dist_Mile_Feature_Dissolved_Select = "Database Connections\\GDB_ASSETS.sde\\GDB_Assets.ASSETS_ADMIN.Dist_Mile_Feature_Dissolved_Select"
Dist_Mile_Feature_Dissolved_Select_Field_Change = "Database Connections\\GDB_ASSETS.sde\\GDB_Assets.ASSETS_ADMIN.Dist_Mile_Feature_Dissolved_Select"
GDB_Assets_ASSETS_ADMIN_Dist_Mile_Feature_Dissolved_Select = "Database Connections\\GDB_ASSETS.sde\\GDB_Assets.ASSETS_ADMIN.Dist_Mile_Feature_Dissolved_Select"
OPSDistrictTowns_Feature_Joined = "GDB_Assets.ASSETS_ADMIN.Boundary_OPSDistrictTowns"
Const_Reg_Feature_Joined = "Database Connections\\GDB_ASSETS.sde\\GDB_Assets.ASSETS_ADMIN.Boundary_ConstructionRegions"

# Process: Dissolve
arcpy.Dissolve_management(District_Mileages_Feature, Dist_Mile_Feature_Dissolved, "DISTRICT", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Select
arcpy.Select_analysis(Dist_Mile_Feature_Dissolved, Dist_Mile_Feature_Dissolved_Select, "DISTRICT NOT LIKE 'HQ'")

# Process: Calculate Field
arcpy.CalculateField_management(Dist_Mile_Feature_Dissolved_Select, "DISTRICT", "Right([DISTRICT],1)", "VB", "")

# Process: Table to Table (2)
arcpy.TableToTable_conversion(Contact_Dist_View, GDB_ASSETS_sde, "Dist_Cont_GeoTable", "", "DistrictId \"DistrictId\" true true false 2 Short 0 5 ,First,#,Database Connections\\GDB_ASSETS.sde\\GDB_Assets.Assets_Admin.Contact_Dist,DistrictId,-1,-1;DistrictName \"DistrictName\" true true false 20 Text 0 0 ,First,#,Database Connections\\GDB_ASSETS.sde\\GDB_Assets.Assets_Admin.Contact_Dist,DistrictName,-1,-1;DistrictPhone \"DistrictPhone\" true true false 14 Text 0 0 ,First,#,Database Connections\\GDB_ASSETS.sde\\GDB_Assets.Assets_Admin.Contact_Dist,DistrictPhone,-1,-1;DistrictDTA \"DistrictDTA\" true true false 50 Text 0 0 ,First,#,Database Connections\\GDB_ASSETS.sde\\GDB_Assets.Assets_Admin.Contact_Dist,DistrictDTA,-1,-1;DistrictGM \"DistrictGM\" true true false 50 Text 0 0 ,First,#,Database Connections\\GDB_ASSETS.sde\\GDB_Assets.Assets_Admin.Contact_Dist,DistrictGM,-1,-1", "")

# Process: Join Field (3)
arcpy.JoinField_management(Dist_Mile_Feature_Dissolved_Select_Field_Change, "DISTRICT", Dist_Cont_GeoTable, "DistrictId", "DistrictPhone;DistrictDTA;DistrictGM")

# Process: Delete Field
arcpy.DeleteField_management(GDB_Assets_ASSETS_ADMIN_Dist_Mile_Feature_Dissolved_Select, "DISTRICT")

# Process: Join Field (2)
arcpy.JoinField_management(OPSDistrictTowns_Feature, "DIST", Dist_Cont_GeoTable, "DistrictId", "DistrictPhone;DistrictDTA;DistrictGM")

# Process: Delete Field (2)
arcpy.DeleteField_management(OPSDistrictTowns_Feature_Joined, "GDB_Gen_VTRANS_ADMIN_Boundary_O;PERIMETER;TBHASH_;TBHASH_ID;RPC;FIPS6;DIST;CTCODE")

# Process: Table to Table
arcpy.TableToTable_conversion(Const_Reg_Contact_View, GDB_ASSETS_sde, "Const_Reg_Contact_GeoTable", "", "FullName \"FullName\" true true false 255 Text 0 0 ,First,#,Database Connections\\GDB_ASSETS.sde\\GDB_Assets.Assets_Admin.Contact_Const,FullName,-1,-1;EmailAddress \"EmailAddress\" true true false 50 Text 0 0 ,First,#,Database Connections\\GDB_ASSETS.sde\\GDB_Assets.Assets_Admin.Contact_Const,EmailAddress,-1,-1;PhoneWork \"PhoneWork\" true true false 50 Text 0 0 ,First,#,Database Connections\\GDB_ASSETS.sde\\GDB_Assets.Assets_Admin.Contact_Const,PhoneWork,-1,-1;JobTitle \"JobTitle\" true true false 50 Text 0 0 ,First,#,Database Connections\\GDB_ASSETS.sde\\GDB_Assets.Assets_Admin.Contact_Const,JobTitle,-1,-1;Region \"Region\" true false false 9 Text 0 0 ,First,#,Database Connections\\GDB_ASSETS.sde\\GDB_Assets.Assets_Admin.Contact_Const,Region,-1,-1", "")

# Process: Join Field
arcpy.JoinField_management(Const_Reg_Feature, "REGION", Const_Reg_Contact_GeoTable, "Region", "FullName;EmailAddress;PhoneWork;JobTitle")

# Process: Delete Field (3)
arcpy.DeleteField_management(Const_Reg_Feature_Joined, "GDB_Gen_VTRANS_ADMIN_Boundary_C;PERIMETER;REGION;area_1;GDB_Gen_VTRANS_ADMIN_Boundary_1;Shape_STArea__;Shape_STLength__")

